version: '3.7'

services:
  pytest_robot_ubuntu:
    container_name: sh_qa_pytest_robot_ubuntu
    image: sh_qa_pytest_robot_ubuntu
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.ubuntu.pytest.robot
      args:
        buildversion: 1
    ports:
      - "3000:3000"
    networks:
      sh_qa_net:
        ipv4_address: 10.6.0.11
    volumes:
      - ./src:/opt
    tty: true
    command: tail -F /dev/null

  flasky:    
    build:
      context: ./Flasky-master
      dockerfile: Dockerfile
      args:
        buildversion: 1
    ports:
      - "8082:8080"
    networks:
      sh_qa_net:
        ipv4_address: 10.6.0.13
    volumes:
      - ./Flasky-master:/app
    tty: true
    command: tail -F /dev/null


networks:
  sh_qa_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1
